# Generated by Django 5.0.4 on 2025-05-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escuderia', models.CharField(max_length=100)),
                ('piloto', models.CharField(max_length=100)),
                ('rendimiento', models.FloatField()),
                ('genero', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
