# Generated by Django 5.0.4 on 2025-05-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formula1',
            old_name='piloto',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='formula1',
            name='genero',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='formula1',
            name='rendimiento',
            field=models.IntegerField(),
        ),
    ]
