# Generated by Django 5.0.4 on 2025-05-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula1', '0002_rename_piloto_formula1_nombre_alter_formula1_genero_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formula1',
            old_name='nombre',
            new_name='piloto',
        ),
        migrations.AlterField(
            model_name='formula1',
            name='genero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='formula1',
            name='rendimiento',
            field=models.FloatField(),
        ),
    ]
