# Generated by Django 5.0.4 on 2025-06-10 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='anio_publicacion',
            new_name='año_publicacion',
        ),
    ]
